name:           coinbase-pro
version:        0.5.0.0
description:    API to coinbase-pro
homepage:       https://github.com/mdunnio/coinbase-pro#readme
bug-reports:    https://github.com/mdunnio/coinbase-pro/issues
author:         Michael Dunn <michaelsdunn1@gmail.com>
maintainer:     Michael Dunn <michaelsdunn1@gmail.com>
copyright:      2019 Michael Dunn <michaelsdunn1@gmail.com>
license:        MIT
license-file:   LICENSE
build-type:     Simple

extra-source-files:
    README.md

github: https://github.com/mdunnio/coinbase-pro

dependencies:
  - base                 >= 4.7  && < 5
  - HsOpenSSL            >= 0.11 && < 0.12
  - aeson                >= 1.2  && < 1.4
  - aeson-casing         >= 0.1  && < 0.2
  - async                >= 2.1  && < 2.3
  - binary               >= 0.8  && < 0.9
  - bytestring           >= 0.10 && < 0.11
  - containers           >= 0.5  && < 0.6
  - cryptonite           >= 0.24 && < 0.26
  - http-api-data        >= 0.3  && < 0.4
  - http-client          >= 0.5  && < 0.6
  - http-client-tls      >= 0.3  && < 0.4
  - http-streams         >= 0.8  && < 0.9
  - http-types           >= 0.12 && < 0.13
  - io-streams           >= 1.5  && < 1.6
  - memory               >= 0.14 && < 0.15
  - network              >= 2.6  && < 2.7
  - servant              >= 0.14 && < 0.15
  - servant-client       >= 0.14 && < 0.15
  - servant-client-core  >= 0.14 && < 0.15
  - text                 >= 1.2  && < 1.3
  - time                 >= 1.8  && < 1.9
  - transformers         >= 0.5  && < 0.6
  - unagi-streams        >= 0.2  && < 0.3
  - unordered-containers >= 0.2  && < 0.3
  - vector               >= 0.12 && < 0.13
  - websockets           >= 0.12 && < 0.13
  - wuss                 >= 1.1  && < 1.2

library:
  source-dirs: src/lib/
  ghc-options: -Wall -fwarn-tabs -O2 -funbox-strict-fields

executables:
  test-request:
    main: Main.hs
    source-dirs: src/example/request/
    dependencies:
      - coinbase-pro

  test-stream:
    main: Main.hs
    source-dirs: src/example/stream/
    dependencies:
      - coinbase-pro
