name:           coinbase-pro
version:        0.3.1.0
description:    API to coinbase-pro
homepage:       https://github.com/michaelsdunn1/coinbase-pro#readme
bug-reports:    https://github.com/michaelsdunn1/coinbase-pro/issues
author:         Michael Dunn <michaelsdunn1@gmail.com>
maintainer:     Michael Dunn <michaelsdunn1@gmail.com>
copyright:      2019 Michael Dunn <michaelsdunn1@gmail.com>
license:        MIT
license-file:   LICENSE
build-type:     Simple

extra-source-files:
    README.md

github: https://github.com/michaelsdunn1/coinbase-pro

dependencies:
  - base
  - HsOpenSSL
  - aeson
  - aeson-casing
  - async
  - binary
  - bytestring
  - containers
  - cryptonite
  - http-api-data
  - http-client
  - http-client-tls
  - http-streams
  - http-types
  - io-streams
  - memory
  - network
  - servant
  - servant-client
  - text
  - time
  - transformers
  - unagi-streams
  - unordered-containers
  - vector
  - websockets
  - wuss

library:
  source-dirs: src/lib/
  ghc-options: -Wall -fwarn-tabs -O2 -funbox-strict-fields
