resolver: lts-16.7

ghc-options:
  "$locals": -Wall

packages:
- .

extra-deps:
  - unagi-streams-0.2.6
  - unagi-chan-0.4.1.3

system-ghc: false

extra-include-dirs: ["/usr/local/opt/openssl/include"]
extra-lib-dirs: ["/usr/local/opt/openssl/lib"]
